### ISSUE TITLE
ChemistryExcitedState active space issue

### ISSUE THREAD

**Issue by shivupa** [tequilahub/tequila-tutorials-unformatted#13]
Hi I was running into the following issue while running the excited state example.

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_177699/221487425.py in <module>
     10     active = {"b1u": [0], "b2u": [0]}
     11     mol = tq.chemistry.Molecule(geometry=geomstring.format(R=R), basis_set="6-31g", active_orbitals=active)
---> 12     H = mol.make_hamiltonian()
     13     results = []
     14     for i in range(2):

~/.local/lib/python3.9/site-packages/tequila/quantumchemistry/qc_base.py in make_hamiltonian(self, occupied_indices, active_indices, threshold)
    940 
    941         fop = openfermion.transforms.get_fermion_operator(
--> 942             self.molecule.get_molecular_hamiltonian(occupied_indices, active_indices))
    943         try:
    944             qop = self.transformation(fop)

~/.local/lib/python3.9/site-packages/openfermion/chem/molecular_data.py in get_molecular_hamiltonian(self, occupied_indices, active_indices)
    900             constant = self.nuclear_repulsion
    901         else:
--> 902             core_adjustment, one_body_integrals, two_body_integrals = self. \
    903                 get_active_space_integrals(occupied_indices, active_indices)
    904             constant = self.nuclear_repulsion + core_adjustment

~/.local/lib/python3.9/site-packages/openfermion/chem/molecular_data.py in get_active_space_integrals(self, occupied_indices, active_indices)
    872         # Get integrals.
    873         one_body_integrals, two_body_integrals = self.get_integrals()
--> 874         return reps.get_active_space_integrals(one_body_integrals,
    875                                                two_body_integrals,
    876                                                occupied_indices, active_indices)

~/.local/lib/python3.9/site-packages/openfermion/ops/representations/interaction_operator.py in get_active_space_integrals(one_body_integrals, two_body_integrals, occupied_indices, active_indices)
    257         for v in active_indices:
    258             for i in occupied_indices:
--> 259                 one_body_integrals_new[u, v] += (
    260                     2 * two_body_integrals[i, u, v, i] -
    261                     two_body_integrals[i, u, i, v])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

It seems like openfermion is expecting a list rather than a dictionary? When reading the [tequilla code base](https://github.com/aspuru-guzik-group/tequila/blob/0637f83c354c70bac95acef5a41ffa7cf3c48e3b/src/tequila/quantumchemistry/qc_base.py#L31) it seemed like this should be a list too? Any advice on how to proceed?

**Comment by kottmanj** [comment]
Hi, thanks for reaching out. I just tested it and it seems to work for me.
Can you try updating tequila, openfermion and cirq (cirq because openfermion needs some cirq structures).

pip install --update git+https://github.com/aspuru-guzik-group/tequila.git
pip install --update openfermion
pip install --update cirq

Can you try that and let me know if the problem still exist (or if it was solved).

my versions:
tequila was head of the master branch (the command above will give you the same)
cirq was 0.12.0
openfermion was 1.1.0

**Comment by shivupa** [comment]
```
In [4]: tequila.__version__
Out[4]: '1.6.0'
In [5]: cirq.__version__
Out[5]: '0.12.0'
In [6]: openfermion.__version__
Out[6]: '1.1.0'
```
Yup I am on the same, but I have the same issue.

**Comment by kottmanj** [comment]
To be sure: You have psi4 installed? 
The chemistry modules also work with pyscf, but the module is less advanced and does not understand the irreps for the active spaces.
It kinda looks like that is the problem.

With PySCF you can just set the total indices of the active spaces, e.g. active=[2,3]
the rest stays the same.

If you are using a conda environment: conda install psi4 -c psi4
tequila will automatically use it as default for basis_set chemistry if it is there.
If you want to be sure:
mol = tq.chemistry.Molecule(geometry=geomstring.format(R=R), basis_set="6-31g", active_orbitals=active, backend="psi4")

Or alternatively construct the active spaces without the irrep information (kind of depends what you want, I assume right now the main goal is just to get the tutorial to run). So either install psi4 or replace active with active=[2,3] or use a smaller molecule with no active space (e.g. H2).

Let me know if it works after one of those :-)

**Comment by shivupa** [comment]
That is the problem. Sorry I saw that this worked with psi4 and pyscf so I only had pyscf installed. I'll close this and only reopen it if I run into trouble.

I did try the list and using no active space. Those both worked.

**Comment by kottmanj** [comment]
Cool! 
Good reminder for me to put a small disclaimer in the tutorial .... or maybe make it work for both backends :-)
