### ISSUE TITLE
problem in F12Correction

### ISSUE THREAD

**Issue by taoyx23** [tequilahub/tequila-tutorials-unformatted#22]
Hi all,
I'm reading F12Correction.ipynb, and when I run the `Active` procedure for the F12 correction, the following problem occurs:

Set up universal f12-correction using a HF-RI-basis, with an active space as OBS.
Traceback (most recent call last):
  File "/raid/home/taoyx/work/basis/hea/tequila/active/activespace.py", line 33, in <module>
    corr_active[l] = mol.perturbative_f12_correction(
  File "/raid/home/taoyx/software/anaconda3/envs/tequila/lib/python3.9/site-packages/tequila/quantumchemistry/psi4_interface.py", line 680, in perturbative_f12_correction
    return correction.compute()
  File "/raid/home/taoyx/software/anaconda3/envs/tequila/lib/python3.9/site-packages/tequila/quantumchemistry/f12_corrections/_f12_correction_psi4.py", line 300, in compute
    h, g, r = self.setup_tensors_active()
  File "/raid/home/taoyx/software/anaconda3/envs/tequila/lib/python3.9/site-packages/tequila/quantumchemistry/f12_corrections/_f12_correction_psi4.py", line 102, in setup_tensors_active
    r_elems = numpy.asarray(mints.mo_f12(correlationFactor, C_RI, C_RI, C_RI, C_RI))
TypeError: mo_f12(): incompatible function arguments. The following argument types are supported:
    1. (self: psi4.core.MintsHelper, corr: List[Tuple[float, float]], C1: psi4.core.Matrix, C2: psi4.core.Matrix, C3: psi4.core.Matrix, C4: psi4.core.Matrix) -> psi4.core.Matrix

Invoked with: <psi4.core.MintsHelper object at 0x7f3094d8afb0>, <psi4.core.FittedSlaterCorrelationFactor object at 0x7f309949a7b0>, <psi4.core.Matrix object at 0x7f3092ec4ae0>, <psi4.core.Matrix object at 0x7f3092ec4ae0>, <psi4.core.Matrix object at 0x7f3092ec4ae0>, <psi4.core.Matrix object at 0x7f3092ec4ae0>

The version of tequila-basic is 1.8.8, and the version of psi4 is 1.7+6ce35a5. Let me know if I do something wrong.

Thanks

**Comment by kottmanj** [comment]
Hi,

thanks for the feedback. Could you do me the favor and repost this issue in the main repository (https://github.com/tequilahub/tequila) -- this is just for me to keep the overview.

Regarding the issue itself, I'm gonna contact @philipp-q who did the f12 implementation. 
As far as I remember, we had the problem that for some LCAO techniques it was necessary to introduce some changes into psi4, so a specialized implementation is potentially needed. I am however not 100% sure right now, if this is the case here (from the error message, it looks a little bit like it).

**Comment by kottmanj** [comment]
DId you use this fork of psi4 https://github.com/philipp-q/psi4/tree/ri_space or the standard conda installation?

**Comment by taoyx23** [comment]
> DId you use this fork of psi4 https://github.com/philipp-q/psi4/tree/ri_space or the standard conda installation?

Thank you for your reply. And I used "conda install psi4 -c psi4", that refers to https://github.com/tequilahub/tequila/tree/master#quantumchemistry.

**Comment by kottmanj** [comment]
moving to main repo. Thanks for re-posting there :-)
